import {Footer} from "../components/footer.jsx";
import {Header} from "../components/header.jsx";
import { Inter as FontSans } from "next/font/google"
import { cn } from "lib/utils"
import "styles/globals.css";
import "styles/loading.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.svg'
  }
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <Header />
        <div className="flex max-full mx-auto flex-col justify-center py-0 min-h-screen">
          <main className="flex-1 flex justify-center">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
